events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    client_max_body_size 20m;

    upstream frontend {
        server frontend:3000;
    }

    upstream backend {
        server backend:5223;
    }

    server {
        listen 80;

        return 301 https://$host:8443$request_uri;
    }

    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/ssl/localhost.pem;
        ssl_certificate_key /etc/nginx/ssl/localhost-key.pem;

        ssl_protocols TLSv1.2 TLSv1.3;

        location /api/auth/callback/ {
            proxy_pass http://frontend;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Port 8443;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://backend;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Port 8443;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /assets/ {
            alias /usr/share/nginx/html/assets/;
            expires 7d;
            add_header Cache-Control "public";
            try_files $uri =404;
        }

        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Port 8443;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}